all:
  hosts:
    node1:
      ansible_host: 192.168.1.20
      ip: 192.168.1.20
      access_ip: 192.168.1.20
    node2:
      ansible_host: 192.168.1.30
      ip: 192.168.1.30
      access_ip: 192.168.1.30

  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
        node2:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
